### ISSUE TITLE
no source files show up after trying to clone the heroku project for local modification

### ISSUE THREAD

**Issue by kevinmting** [groupme/bot-tutorial-nodejs#13]
I think I followed the tutorial exactly, but when I executed:
   "heroku git:clone MY_APP_NAME" 

I ended up not getting any source files and instead saw this message:
   "warning: You appear to have cloned an empty repository."

any ideas what could be causing this?

also very new to this stuff, what do i need to install to run foreman? (I'm on a Mac)

thanks!

**Comment by buddymilford** [comment]
I had the same issue. I followed this link and it solved my problem.

https://kb.heroku.com/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository

**Comment by kevinmting** [comment]
@buddymilford  I eventually ended up figuring this out after playing around for a while, but good to know this is a known issue and have the formal kb instruction.  thanks for the reply!

**Comment by cgilker** [comment]
@buddymilford the link is gone?
